# Website settings
url: "https://www.samitopal.com"

# Internal nav
nav:
  main:
 #   writing: "/writing"
 #   speaking: "/speaking"
 #   projects: "/projects"
     cv: "https://about.samitopal.com"
 # writing:
 #   all: "/writing"
 #   popular: "/writing/popular"
 #   tags: "/writing/tags"
 #   rss: "/feed.xml"

# Bio settings
name: "Sami Topal"
description: " "
thumbnail_path: "profile-photos/samitopal.jpg"
#bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
#hello_startup_url: "https://www.hello-startup.net/"
#website_repo_url: "https://github.com/brikis98/yevgeniy-brikman-homepage"
#atomic_squirrel_url: "https://www.atomic-squirrel.net/"
#gruntwork_url: "https://www.gruntwork.io/"
#terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
#terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
    cv:
      url: "https://about.samitopal.com"
      label: "CV"
      icon: "user-tie"
  linkedin:
    url: "https://www.linkedin.com/in/samitopal"
    label: "LinkedIn"
    icon: "linkedin-square"
  email:
    url: "mailto:samitopal@gmail.com"
    label: "Email"
    value: "samitopal@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
